nama = input("nama : ")
ttl = input("tempat tanggal lahir : ")
alamat = input("alamat : ")
no_hp = input("no hp : ")
prodi = input("prodi : ")
hobi = input("hobi : ")
print("=================")
print("Biodata Diri")
print(f"Nama lengkap: {nama}")
print(f"TTL: {ttl}")
print(f"Alamat: {alamat}")
print(f"No. Hp: {no_hp}")
print(f"Program Study: {prodi}")
print(f"hobi: {hobi}")
print("fauzan wahyu")
